// Package generate turns a Runnable contract into Go source: the typed input
// and output bindings the harness and the author share, and the handler
// scaffold the author owns.
package generate

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/codefly-dev/core/resources"
)

// Type names of a generated binding file: the two payload roots and the two
// carriers of a field the contract declares optional.
const (
	inputType    = "Input"
	outputType   = "Output"
	optionalType = "Optional"
	presentType  = "Present"
)

// Bindings renders the typed Go bindings of a contract's input and output.
//
// The bounded profile maps to Go by value type and by the two declarations the
// contract keeps independent: optional means the key may be absent, nullable
// means the value may be null. A field that is only optional is a Present,
// omitted when absent and refusing the null it does not declare, a field that
// is only nullable is a pointer written as null, and a field that is both is an
// Optional, which round-trips absent and null as the distinct states they are.
//
// A Go nil slice encodes as null whether or not the array field is declared
// nullable, so an array the contract never allows to be null is caught by
// output validation rather than by its type.
func Bindings(pkg string, contract *resources.RunnableContract) ([]byte, error) {
	if err := contract.Validate(); err != nil {
		return nil, err
	}
	g := &generator{declared: make(map[string]struct{})}
	if err := g.enqueue(inputType, "is the typed invocation input declared by the contract.", contract.Input.Fields); err != nil {
		return nil, err
	}
	if err := g.enqueue(outputType, "is the typed invocation output declared by the contract.", contract.Output.Fields); err != nil {
		return nil, err
	}
	if err := g.run(); err != nil {
		return nil, err
	}

	var b strings.Builder
	b.WriteString("// Code generated by runnable-go. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n", pkg)
	switch {
	case g.usesPresent:
		b.WriteString("\nimport (\n\t\"encoding/json\"\n\t\"errors\"\n)\n")
	case g.usesOptional:
		b.WriteString("\nimport \"encoding/json\"\n")
	}
	for _, decl := range g.decls {
		b.WriteString("\n")
		b.WriteString(decl)
	}
	if g.usesOptional {
		b.WriteString("\n")
		b.WriteString(optionalDeclaration)
	}
	if g.usesPresent {
		b.WriteString("\n")
		b.WriteString(presentDeclaration)
	}
	return format.Source([]byte(b.String()))
}

type pending struct {
	name   string
	doc    string
	fields []*resources.RunnableField
}

type generator struct {
	decls        []string
	queue        []pending
	declared     map[string]struct{}
	usesOptional bool
	usesPresent  bool
}

// enqueue schedules one object type. Nested objects are rendered after the type
// that references them, so a binding file reads from the payload root down.
func (g *generator) enqueue(name string, doc string, fields []*resources.RunnableField) error {
	if _, exists := g.declared[name]; exists {
		return fmt.Errorf("type %q is generated twice: rename the field it comes from", name)
	}
	g.declared[name] = struct{}{}
	g.queue = append(g.queue, pending{name: name, doc: doc, fields: fields})
	return nil
}

func (g *generator) run() error {
	for len(g.queue) > 0 {
		next := g.queue[0]
		g.queue = g.queue[1:]
		decl, err := g.structure(next)
		if err != nil {
			return err
		}
		g.decls = append(g.decls, decl)
	}
	return nil
}

func (g *generator) structure(p pending) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s %s\n", p.name, p.doc)
	fmt.Fprintf(&b, "type %s struct {\n", p.name)

	taken := make(map[string]string, len(p.fields))
	for _, field := range p.fields {
		name := exported(field.Name)
		if name == "" {
			return "", fmt.Errorf("field %q has no Go identifier", field.Name)
		}
		if previous, clash := taken[name]; clash {
			return "", fmt.Errorf("fields %q and %q both generate Go field %q", previous, field.Name, name)
		}
		taken[name] = field.Name

		declared, err := g.fieldType(p.name+name, field)
		if err != nil {
			return "", err
		}
		if field.Description != "" {
			for _, line := range strings.Split(field.Description, "\n") {
				fmt.Fprintf(&b, "\t// %s\n", line)
			}
		}
		fmt.Fprintf(&b, "\t%s %s `json:%q`\n", name, declared, jsonTag(field))
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// fieldType is the Go type a field is declared with, optionality and
// nullability included. hint names the type a nested object is generated as.
func (g *generator) fieldType(hint string, field *resources.RunnableField) (string, error) {
	base, err := g.valueType(hint, field)
	if err != nil {
		return "", err
	}
	switch {
	case field.Optional && field.Nullable:
		g.usesOptional = true
		return fmt.Sprintf("%s[%s]", optionalType, base), nil
	case field.Optional:
		g.usesPresent = true
		return fmt.Sprintf("%s[%s]", presentType, base), nil
	case field.Nullable:
		return "*" + base, nil
	default:
		return base, nil
	}
}

func (g *generator) valueType(hint string, field *resources.RunnableField) (string, error) {
	switch field.Type {
	case resources.RunnableFieldString:
		return "string", nil
	case resources.RunnableFieldInteger:
		return "int64", nil
	case resources.RunnableFieldBoolean:
		return "bool", nil
	case resources.RunnableFieldObject:
		if err := g.enqueue(hint, "is a nested object of the contract.", field.Fields); err != nil {
			return "", err
		}
		return hint, nil
	case resources.RunnableFieldArray:
		element, err := g.valueType(hint+"Item", field.Items)
		if err != nil {
			return "", err
		}
		if field.Items.Nullable {
			element = "*" + element
		}
		return "[]" + element, nil
	}
	return "", fmt.Errorf("field %q has type %q outside the bounded profile", field.Name, field.Type)
}

// jsonTag omits an optional key when it is absent; a nullable-only key is
// always written, as null when it has no value.
func jsonTag(field *resources.RunnableField) string {
	if field.Optional {
		return field.Name + ",omitzero"
	}
	return field.Name
}

// exported turns a contract field name into a Go field name. Contract names are
// identifiers, so the only transformation is underscore-separated capitalization.
func exported(name string) string {
	var b strings.Builder
	for _, part := range strings.Split(name, "_") {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}

const optionalDeclaration = `// Optional carries a field the contract declares both optional and nullable.
// Absent and null are separate states there, so neither may stand for the other.
type Optional[T any] struct {
	// Present is true when the payload carried the key.
	Present bool
	// Value is nil when the key was present and null.
	Value *T
}

// IsZero reports an absent key, which is what omits it from an encoded payload.
func (o Optional[T]) IsZero() bool {
	return !o.Present
}

func (o Optional[T]) MarshalJSON() ([]byte, error) {
	if o.Value == nil {
		return []byte("null"), nil
	}
	return json.Marshal(o.Value)
}

func (o *Optional[T]) UnmarshalJSON(data []byte) error {
	o.Present = true
	if string(data) == "null" {
		o.Value = nil
		return nil
	}
	var value T
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	o.Value = &value
	return nil
}
`

const presentDeclaration = `// Present carries a field the contract declares optional and not nullable: the
// key may be absent, and no value it carries may be null.
//
// It is a value and not a pointer because encoding/json sets a pointer field to
// nil for an explicit null without ever consulting an unmarshaler, which admits
// a null the declaration forbids and leaves it indistinguishable from the key
// being absent.
//
// The value is reachable only through Value, and the zero Present is absent, so
// no literal can spell a key that is absent and carries a value at once.
type Present[T any] struct {
	set   bool
	value T
}

// Value is the state of a key the payload carries.
func Value[T any](value T) Present[T] {
	return Present[T]{set: true, value: value}
}

// Get returns the carried value, and false when the key was absent.
func (p Present[T]) Get() (T, bool) {
	return p.value, p.set
}

// IsZero reports an absent key, which is what omits it from an encoded payload.
func (p Present[T]) IsZero() bool {
	return !p.set
}

// MarshalJSON encodes the carried value. The absent state has no encoding as a
// value: every generated field carries omitzero, so an absent Present is
// omitted with its key and never reaches here. Reaching here absent means the
// value is being encoded where a key cannot be omitted, where null would stand
// in for absent and would itself be a value the declaration forbids.
func (p Present[T]) MarshalJSON() ([]byte, error) {
	if !p.set {
		return nil, errors.New("an absent optional value has no encoding: it is omitted with its key, never written as null")
	}
	return json.Marshal(p.value)
}

func (p *Present[T]) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("value is null but the contract does not declare the field nullable")
	}
	if err := json.Unmarshal(data, &p.value); err != nil {
		return err
	}
	p.set = true
	return nil
}
`
