// Package generate turns a Runnable contract into Go source: the typed input
// and output bindings the harness and the author share, and the handler
// scaffold the author owns.
package generate

import (
	"fmt"
	"go/format"
	"go/token"
	"regexp"
	"strings"

	"github.com/codefly-dev/core/resources"
)

// Type names of a generated binding file: the two payload roots and the two
// carriers of a declaration no plain Go type expresses.
const (
	inputType    = "Input"
	outputType   = "Output"
	optionalType = "Optional"
	presentType  = "Present"
	listType     = "List"
)

// GoRequirement is the toolchain floor of generated bindings, carried in each
// file as a build constraint.
//
// An absent key is omitted by the encoding/json omitzero option, which arrived
// in Go 1.24 and which an older toolchain ignores in silence rather than
// rejecting: every absent optional key would then encode as null, the one
// state the contract keeps distinct from absent. The go directive of the
// author's module does not gate the option, so the constraint is what makes an
// old toolchain fail to build instead of encoding the wrong payload.
const GoRequirement = "go1.24"

// goExported matches the Go field and type names generation emits. encoding/json
// ignores an unexported field, so a contract field that generated one would be
// dropped from every payload rather than rejected; a name that is no
// identifier at all reaches gofmt as a parse error naming neither the field
// nor the reason.
var goExported = regexp.MustCompile(`^[A-Z][A-Za-z0-9_]*$`)

// goIdentifier matches a package name generation may be asked to render into a
// file. A runnable name is a path component, so it may legally carry a dash
// that no Go package name may.
var goIdentifier = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// Bindings renders the typed Go bindings of a contract's input and output.
//
// It takes the contract rather than the whole resources.Runnable because it
// validates exactly what it renders: Runnable.Validate additionally demands a
// pinned agent, an entrypoint and an execution block, none of which change a
// byte of the output, so taking the Runnable would reject declarations that
// generate perfectly well.
//
// The bounded profile maps to Go by value type and by the two declarations the
// contract keeps independent: optional means the key may be absent, nullable
// means the value may be null. A field that is only optional is a Present,
// omitted when absent and refusing the null it does not declare, a field that
// is only nullable is a pointer written as null, and a field that is both is an
// Optional, which round-trips absent and null as the distinct states they are.
//
// An array is a List and not a plain Go slice. A nil slice encodes as null,
// and only a field the contract declares nullable has a null state to encode,
// so a nil slice would put a value on the wire that the declaration forbids
// and that no decoder on the other side has to accept. A List encodes an unset
// array as the empty array it is and refuses to decode a null one; where the
// contract does declare the array nullable, the null state is the nil *List.
func Bindings(pkg string, contract *resources.RunnableContract) ([]byte, error) {
	if err := validatePackageName(pkg); err != nil {
		return nil, err
	}
	if err := contract.Validate(); err != nil {
		return nil, err
	}
	g := &generator{declared: make(map[string]string)}
	if err := g.enqueue(inputType, "input", "is the typed invocation input declared by the contract.", contract.Input.Fields); err != nil {
		return nil, err
	}
	if err := g.enqueue(outputType, "output", "is the typed invocation output declared by the contract.", contract.Output.Fields); err != nil {
		return nil, err
	}
	if err := g.run(); err != nil {
		return nil, err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "//go:build %s\n\n", GoRequirement)
	b.WriteString("// Code generated by runnable-go. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n", pkg)
	if g.usesCarrier() {
		b.WriteString("\nimport (\n\t\"encoding/json\"\n\t\"errors\"\n)\n")
	}
	for _, decl := range g.decls {
		b.WriteString("\n")
		b.WriteString(decl)
	}
	if g.usesOptional {
		b.WriteString("\n")
		b.WriteString(optionalDeclaration)
	}
	if g.usesPresent {
		b.WriteString("\n")
		b.WriteString(presentDeclaration)
	}
	if g.usesList {
		b.WriteString("\n")
		b.WriteString(listDeclaration)
	}
	return format.Source([]byte(b.String()))
}

// validatePackageName rejects a package name that would reach gofmt as a parse
// error, or that would inject whatever it carries into a file marked as
// generated.
func validatePackageName(pkg string) error {
	if !goIdentifier.MatchString(pkg) || pkg == "_" || token.IsKeyword(pkg) {
		return fmt.Errorf("package name %q is not a Go package identifier", pkg)
	}
	return nil
}

type pending struct {
	name string
	// path is the contract path this type is generated from, such as
	// input.options or input.records[]. It names the declaration an author can
	// act on; the Go type name names nothing they wrote.
	path   string
	doc    string
	fields []*resources.RunnableField
}

type generator struct {
	decls []string
	queue []pending
	// declared maps a generated Go type name to the contract path that
	// produced it, so a collision reports both paths.
	declared     map[string]string
	usesOptional bool
	usesPresent  bool
	usesList     bool
}

// usesCarrier reports whether the file declares Optional, Present or List,
// which are what the generated imports are for.
func (g *generator) usesCarrier() bool {
	return g.usesOptional || g.usesPresent || g.usesList
}

// enqueue schedules one object type. Nested objects are rendered after the type
// that references them, so a binding file reads from the payload root down.
func (g *generator) enqueue(name string, path string, doc string, fields []*resources.RunnableField) error {
	if previous, exists := g.declared[name]; exists {
		return fmt.Errorf("contract paths %s and %s both generate Go type %q: rename one of the fields", previous, path, name)
	}
	g.declared[name] = path
	g.queue = append(g.queue, pending{name: name, path: path, doc: doc, fields: fields})
	return nil
}

func (g *generator) run() error {
	for len(g.queue) > 0 {
		next := g.queue[0]
		g.queue = g.queue[1:]
		decl, err := g.structure(next)
		if err != nil {
			return err
		}
		g.decls = append(g.decls, decl)
	}
	return nil
}

func (g *generator) structure(p pending) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s %s\n", p.name, p.doc)
	fmt.Fprintf(&b, "type %s struct {\n", p.name)

	taken := make(map[string]string, len(p.fields))
	for _, field := range p.fields {
		path := p.path + "." + field.Name
		name := exported(field.Name)
		if !goExported.MatchString(name) {
			return "", fmt.Errorf("contract field %s has no exported Go identifier: %q generates %q", path, field.Name, name)
		}
		if previous, clash := taken[name]; clash {
			return "", fmt.Errorf("fields %q and %q both generate Go field %q", previous, field.Name, name)
		}
		taken[name] = field.Name

		declared, err := g.fieldType(p.name+name, path, field)
		if err != nil {
			return "", err
		}
		if field.Description != "" {
			for _, line := range strings.Split(field.Description, "\n") {
				fmt.Fprintf(&b, "\t// %s\n", line)
			}
		}
		fmt.Fprintf(&b, "\t%s %s `json:%q`\n", name, declared, jsonTag(field))
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// fieldType is the Go type a field is declared with, optionality and
// nullability included. hint names the type a nested object is generated as and
// path names the contract declaration it comes from.
func (g *generator) fieldType(hint string, path string, field *resources.RunnableField) (string, error) {
	base, err := g.valueType(hint, path, field)
	if err != nil {
		return "", err
	}
	switch {
	case field.Optional && field.Nullable:
		g.usesOptional = true
		return fmt.Sprintf("%s[%s]", optionalType, base), nil
	case field.Nullable:
		// The pointer is the null state: nil is written as null.
		return "*" + base, nil
	case field.Optional:
		// Present is the absent state, which omitzero omits. It is a value
		// and not a pointer because encoding/json sets a pointer field to nil
		// for an explicit null without consulting an unmarshaler, which would
		// admit the null this field does not declare and leave it
		// indistinguishable from the key being absent.
		g.usesPresent = true
		return fmt.Sprintf("%s[%s]", presentType, base), nil
	default:
		return base, nil
	}
}

func (g *generator) valueType(hint string, path string, field *resources.RunnableField) (string, error) {
	switch field.Type {
	case resources.RunnableFieldString:
		return "string", nil
	case resources.RunnableFieldInteger:
		return "int64", nil
	case resources.RunnableFieldBoolean:
		return "bool", nil
	case resources.RunnableFieldObject:
		if err := g.enqueue(hint, path, "is a nested object of the contract.", field.Fields); err != nil {
			return "", err
		}
		return hint, nil
	case resources.RunnableFieldArray:
		element, err := g.valueType(hint+"Item", path+"[]", field.Items)
		if err != nil {
			return "", err
		}
		if field.Items.Nullable {
			element = "*" + element
		}
		g.usesList = true
		return fmt.Sprintf("%s[%s]", listType, element), nil
	}
	return "", fmt.Errorf("contract field %s has type %q outside the bounded profile", path, field.Type)
}

// jsonTag omits an optional key when it is absent; a nullable-only key is
// always written, as null when it has no value.
func jsonTag(field *resources.RunnableField) string {
	if field.Optional {
		return field.Name + ",omitzero"
	}
	return field.Name
}

// exported turns a contract field name into a Go field name. Contract names are
// identifiers, so the only transformation is underscore-separated capitalization.
//
// This rule is shared with the other runnable agents: an author reading the Go
// and the Python bindings of one contract must see the same names. It is
// duplicated in runnable-python pkg/generate/types.go (camel and nestedName)
// and belongs in core, which owns the shared protocol and types.
// TestNamingIsTheSharedCrossLanguageRule pins it until it moves there.
func exported(name string) string {
	var b strings.Builder
	for _, part := range strings.Split(name, "_") {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}

const optionalDeclaration = `// Optional carries a field the contract declares both optional and nullable.
// Absent, null and set are three separate states there, so none may stand for
// another.
//
// The states are reachable only through Absent, Null and Set, and the zero
// Optional is absent, so no combination of fields can spell a state the
// contract does not have.
type Optional[T any] struct {
	present bool
	value   *T
}

// Absent is the state of a key the payload does not carry. It is the zero
// Optional.
func Absent[T any]() Optional[T] {
	return Optional[T]{}
}

// Null is the state of a key the payload carries as null.
func Null[T any]() Optional[T] {
	return Optional[T]{present: true}
}

// Set is the state of a key the payload carries with a value.
func Set[T any](value T) Optional[T] {
	return Optional[T]{present: true, value: &value}
}

// Present reports whether the payload carried the key at all.
func (o Optional[T]) Present() bool {
	return o.present
}

// Get returns the carried value, and false when the key was absent or null.
func (o Optional[T]) Get() (T, bool) {
	if o.value == nil {
		var zero T
		return zero, false
	}
	return *o.value, true
}

// IsZero reports an absent key, which is what omits it from an encoded payload.
func (o Optional[T]) IsZero() bool {
	return !o.present
}

// MarshalJSON encodes the null and the set state. The absent state has no
// encoding as a value: every generated field carries omitzero, so an absent
// Optional is omitted with its key and never reaches here. Reaching here
// absent means the value is being encoded somewhere a key cannot be omitted,
// where writing null would turn absent into null without saying so.
func (o Optional[T]) MarshalJSON() ([]byte, error) {
	if !o.present {
		return nil, errors.New("an absent optional value has no encoding: it is omitted with its key, never written as null")
	}
	if o.value == nil {
		return []byte("null"), nil
	}
	return json.Marshal(o.value)
}

func (o *Optional[T]) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		o.present, o.value = true, nil
		return nil
	}
	var value T
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	o.present, o.value = true, &value
	return nil
}
`

const listDeclaration = `// List carries an array of the contract.
//
// A nil Go slice encodes as null, and an array is null only where the contract
// declares the field nullable — a state spelled as the nil *List, never as a
// nil List. So an unset List encodes as the empty array it is, and a null
// payload is refused rather than decoded as an empty array.
type List[T any] []T

func (l List[T]) MarshalJSON() ([]byte, error) {
	if l == nil {
		return []byte("[]"), nil
	}
	return json.Marshal([]T(l))
}

func (l *List[T]) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("array is null but the contract does not declare it nullable")
	}
	var values []T
	if err := json.Unmarshal(data, &values); err != nil {
		return err
	}
	*l = values
	return nil
}
`

const presentDeclaration = `// Present carries a field the contract declares optional and not nullable: the
// key may be absent, and no value it carries may be null.
//
// It is a value and not a pointer because encoding/json sets a pointer field to
// nil for an explicit null without ever consulting an unmarshaler, which admits
// a null the declaration forbids and leaves it indistinguishable from the key
// being absent.
//
// The value is reachable only through Value, and the zero Present is absent, so
// no literal can spell a key that is absent and carries a value at once.
type Present[T any] struct {
	set   bool
	value T
}

// Value is the state of a key the payload carries.
func Value[T any](value T) Present[T] {
	return Present[T]{set: true, value: value}
}

// Get returns the carried value, and false when the key was absent.
func (p Present[T]) Get() (T, bool) {
	return p.value, p.set
}

// IsZero reports an absent key, which is what omits it from an encoded payload.
func (p Present[T]) IsZero() bool {
	return !p.set
}

// MarshalJSON encodes the carried value. The absent state has no encoding as a
// value: every generated field carries omitzero, so an absent Present is
// omitted with its key and never reaches here. Reaching here absent means the
// value is being encoded where a key cannot be omitted, where null would stand
// in for absent and would itself be a value the declaration forbids.
func (p Present[T]) MarshalJSON() ([]byte, error) {
	if !p.set {
		return nil, errors.New("an absent optional value has no encoding: it is omitted with its key, never written as null")
	}
	return json.Marshal(p.value)
}

func (p *Present[T]) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("value is null but the contract does not declare the field nullable")
	}
	if err := json.Unmarshal(data, &p.value); err != nil {
		return err
	}
	p.set = true
	return nil
}
`
