package generate

import (
	"fmt"
	"go/format"
	"strings"

	basev0 "github.com/codefly-dev/core/generated/go/codefly/base/v0"
	"github.com/codefly-dev/core/resources"
)

// Files of the generated invocation harness.
const (
	// HarnessFile carries the harness, beside the bindings and the handler it
	// runs. It is in the author's own package rather than a subpackage so the
	// invocation identity can reach the handler through its context without an
	// exported setter the author could call by mistake.
	HarnessFile = "harness.go"
	// CommandDirectory holds the executable a launcher starts. The Go tool
	// ignores a directory whose name begins with a dot or an underscore, so
	// this one cannot be spelled the way the Python agent spells its generated
	// directory.
	CommandDirectory = "codefly"
	// CommandFile is that executable's main package.
	CommandFile = "main.go"
)

// Harness renders the invocation harness of a runnable: the protocol framing,
// the payload validation the bindings do not do, and the process lifecycle a
// launcher observes.
//
// Every fact the harness enforces is rendered into it rather than read at
// runtime from a document beside it. A Go runnable is compiled, so a contract
// carried in a file could be edited after the build that measured it while the
// binary went on honoring the edit; compiled in, the bounds and the release
// identity are covered by the digest of the artifact that carries them.
//
// identity is the release the workspace resolved. Standalone generation has no
// owning workspace and passes nil, which leaves the workspace unchecked at
// invocation time — the same allowance the Python agent makes, because there is
// no resolved workspace to check against.
func Harness(pkg string, runnable *resources.Runnable, identity *basev0.RunnableIdentity) ([]byte, error) {
	if err := validatePackageName(pkg); err != nil {
		return nil, err
	}
	if err := runnable.Contract.Validate(); err != nil {
		return nil, err
	}
	if err := runnable.Execution.Validate(); err != nil {
		return nil, err
	}
	release := runnable.Identity()
	name, module, workspace, version := release.Name, release.Module, "", runnable.Version
	if identity != nil {
		name, module, workspace, version = identity.GetName(), identity.GetModule(), identity.GetWorkspace(), identity.GetVersion()
	}

	var b strings.Builder
	fmt.Fprintf(&b, "//go:build %s\n\n", GoRequirement)
	b.WriteString("// Code generated by runnable-go. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString(harnessImports)

	b.WriteString("\n// The framing this harness implements, and the bounds and policies its\n")
	b.WriteString("// declaration sets. They are constants so the binary cannot be pointed at a\n")
	b.WriteString("// contract other than the one the build measured.\nconst (\n")
	fmt.Fprintf(&b, "\tharnessProtocol = %q\n", resources.RunnableProtocolV1)
	fmt.Fprintf(&b, "\tharnessMaxInputBytes = %d\n", runnable.Execution.MaxInputBytes())
	fmt.Fprintf(&b, "\tharnessMaxOutputBytes = %d\n", runnable.Execution.MaxOutputBytes())
	fmt.Fprintf(&b, "\tharnessRecovery = %q\n", string(runnable.Execution.Recovery))
	fmt.Fprintf(&b, "\tharnessCancellation = %q\n", string(runnable.Execution.Cancellation))
	b.WriteString(")\n")

	b.WriteString("\n// harnessRelease is the release this package implements. An invocation\n")
	b.WriteString("// naming another release is refused rather than run against foreign input,\n")
	b.WriteString("// which is what keeps two installed versions of one runnable apart.\n")
	fmt.Fprintf(&b, "var harnessRelease = Release{Name: %q, Module: %q, Workspace: %q, Version: %q}\n",
		name, module, workspace, version)

	b.WriteString("\n// The declared schemas, enforced against the raw payload before it is\n")
	b.WriteString("// decoded: the bindings carry value types and null states, not required\n")
	b.WriteString("// keys, undeclared keys or the signed 64-bit integer range.\n")
	b.WriteString("var harnessInputSchema = ")
	b.WriteString(renderFields(runnable.Contract.Input.Fields, 0))
	b.WriteString("\n\nvar harnessOutputSchema = ")
	b.WriteString(renderFields(runnable.Contract.Output.Fields, 0))
	b.WriteString("\n")
	b.WriteString(harnessBody)
	return format.Source([]byte(b.String()))
}

// Command renders the executable a launcher starts. It is a separate main
// package because the harness shares the author's package, and a package that
// is imported cannot also be a main.
func Command(pkg string) ([]byte, error) {
	if err := validatePackageName(pkg); err != nil {
		return nil, err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "//go:build %s\n\n", GoRequirement)
	b.WriteString("// Code generated by runnable-go. DO NOT EDIT.\n\n")
	b.WriteString("// Command codefly runs one invocation of the runnable.\npackage main\n\n")
	fmt.Fprintf(&b, "import (\n\t\"os\"\n\n\t%q\n)\n\n", pkg)
	fmt.Fprintf(&b, "func main() {\n\tos.Exit(%s.Main())\n}\n", pkg)
	return format.Source([]byte(b.String()))
}

// renderFields renders one schema as a Go literal.
func renderFields(fields []*resources.RunnableField, depth int) string {
	if len(fields) == 0 {
		return "[]harnessField{}"
	}
	pad := strings.Repeat("\t", depth+1)
	var b strings.Builder
	b.WriteString("[]harnessField{\n")
	for _, field := range fields {
		b.WriteString(pad)
		b.WriteString(renderField(field, depth+1))
		b.WriteString(",\n")
	}
	b.WriteString(strings.Repeat("\t", depth))
	b.WriteString("}")
	return b.String()
}

func renderField(field *resources.RunnableField, depth int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "{name: %q, kind: %q", field.Name, string(field.Type))
	if field.Optional {
		b.WriteString(", optional: true")
	}
	if field.Nullable {
		b.WriteString(", nullable: true")
	}
	switch field.Type {
	case resources.RunnableFieldObject:
		b.WriteString(", fields: ")
		b.WriteString(renderFields(field.Fields, depth))
	case resources.RunnableFieldArray:
		b.WriteString(", items: &harnessField")
		b.WriteString(renderField(field.Items, depth))
	}
	b.WriteString("}")
	return b.String()
}

const harnessImports = `import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/signal"
	"path/filepath"
	"regexp"
	"strings"
	"syscall"
	"time"
)
`

// harnessBody is the part of the harness that does not vary with the contract.
//
// Every declaration it makes beyond the handler's own surface is prefixed,
// because the harness shares the author's package: an unprefixed helper named
// request or validate would collide with whatever the author wrote beside it.
//
// It carries no backquote, being itself a Go raw string literal.
const harnessBody = `
// The environment a launcher adds to this process. Nothing else in it is part
// of the framing.
const (
	harnessEnvProtocol       = "CODEFLY__RUNNABLE_PROTOCOL"
	harnessEnvInvocationPath = "CODEFLY__RUNNABLE_INVOCATION"
	harnessEnvResultPath     = "CODEFLY__RUNNABLE_RESULT"
)

// Exit codes are diagnostics, not outcomes: a launcher classifies an
// invocation from the result document, its own termination reason and the exit
// status together. These are the codes the Python harness reports for the same
// conditions, so one launcher reads both.
const (
	harnessExitCompleted     = 0
	harnessExitInvalidInput  = 64
	harnessExitInvalidOutput = 65
	harnessExitFailed        = 66
	harnessExitTimeout       = 67
	harnessExitInterrupted   = 68
	harnessExitProtocol      = 69
)

// harnessEnvelopeBytes is how much framing is read around the payload bound, so
// an oversized request is refused without being read whole.
const harnessEnvelopeBytes = 64 * 1024

// harnessResultMode leaves to the facility which accounts may read the result.
// A temporary file is private to this process, so the mode is set before the
// rename rather than inherited from it.
const harnessResultMode = 0o644

// Release identifies a runnable release.
type Release struct {
	Name      string
	Module    string
	Workspace string
	Version   string
}

// Invocation is what the caller said about this run. The identity is the
// caller's: an effect recorded under EffectID is the one the caller looks up
// when an outcome is uncertain.
type Invocation struct {
	ID       string
	IntentID string
	EffectID string
	Release  Release
	Deadline time.Time
}

type harnessInvocationKey struct{}

// InvocationFrom returns the invocation the handler is running under.
func InvocationFrom(ctx context.Context) (Invocation, bool) {
	invocation, ok := ctx.Value(harnessInvocationKey{}).(Invocation)
	return invocation, ok
}

// Failure is an operation's explicit, certain failure: the handler knows what
// became of the effect. Every other error leaves the effect unproven, so it
// writes no result at all rather than a failure a caller would trust.
type Failure struct {
	Code    string
	Message string
}

func (f *Failure) Error() string {
	return f.Code + ": " + f.Message
}

// Fail returns the error a handler returns to report a certain failure.
func Fail(code string, message string) error {
	return &Failure{Code: code, Message: message}
}

// harnessOutcome is what one invocation produced, before it becomes a result
// document and an exit code.
type harnessOutcome struct {
	code       int
	encoded    []byte
	failure    *Failure
	diagnostic string
}

// Main runs one invocation and returns the process exit code.
func Main() int {
	// Interruption is taken from the first instant of the process, not from
	// the moment the handler starts. A launcher may signal at any time, and
	// between exec and that moment the default disposition would kill a
	// package that declares it can stop cleanly.
	//
	// A declaration claiming no cancellation installs no handler, so the
	// process dies on the signal and the launcher sees that, rather than this
	// harness reporting an interruption it did not handle.
	interrupted := make(chan os.Signal, 1)
	if harnessCancellation == "signal" {
		signal.Notify(interrupted, os.Interrupt, syscall.SIGTERM)
		defer signal.Stop(interrupted)
	}

	if os.Getenv(harnessEnvProtocol) != harnessProtocol {
		return harnessRefuse(fmt.Sprintf("%s is %q, not %q", harnessEnvProtocol, os.Getenv(harnessEnvProtocol), harnessProtocol))
	}
	invocationPath, err := harnessAbsolutePath(harnessEnvInvocationPath)
	if err != nil {
		return harnessRefuse(err.Error())
	}
	resultPath, err := harnessAbsolutePath(harnessEnvResultPath)
	if err != nil {
		return harnessRefuse(err.Error())
	}
	// A result at this path is this invocation's or it is nothing. Several
	// uncertain outcomes write none, so an earlier attempt's document left
	// here would be read as this run's proven result. A path the harness
	// cannot clear is one it cannot own, so it refuses to start rather than
	// work toward a result it may not be able to report.
	if err := os.Remove(resultPath); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return harnessRefuse(fmt.Sprintf("clear the result path: %v", err))
	}

	raw, err := harnessReadRequest(invocationPath)
	if err != nil {
		return harnessRefuse(err.Error())
	}
	request, err := harnessParseRequest(raw)
	if err != nil {
		return harnessRefuse(err.Error())
	}

	result := harnessInvoke(request, interrupted)
	if result.diagnostic != "" {
		fmt.Fprintf(os.Stderr, "[codefly] %s\n", result.diagnostic)
	}
	document, reported := harnessResultDocument(request, result)
	if !reported {
		return result.code
	}
	if err := harnessWriteResult(resultPath, document); err != nil {
		fmt.Fprintf(os.Stderr, "[codefly] invalid_output: %v\n", err)
		return harnessExitInvalidOutput
	}
	return result.code
}

// harnessRefuse reports a request or an environment that does not satisfy the
// framing. Nothing there is bound to an invocation identity, so there is no
// result to write: the launcher reads the exit code alone.
func harnessRefuse(message string) int {
	fmt.Fprintf(os.Stderr, "[codefly] %s\n", message)
	return harnessExitProtocol
}

func harnessAbsolutePath(variable string) (string, error) {
	value := os.Getenv(variable)
	if value == "" {
		return "", fmt.Errorf("%s is required: the launcher chooses both document paths", variable)
	}
	if !filepath.IsAbs(value) {
		return "", fmt.Errorf("%s must be an absolute path", variable)
	}
	return value, nil
}

// harnessReadRequest reads at most the payload bound plus the framing around
// it. The bound is on the decoded payload, so the encoded document is read to
// the base64 expansion of that bound.
func harnessReadRequest(path string) ([]byte, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open the invocation: %v", err)
	}
	defer file.Close()
	limit := 4*((harnessMaxInputBytes+2)/3) + harnessEnvelopeBytes
	raw, err := io.ReadAll(io.LimitReader(file, int64(limit)+1))
	if err != nil {
		return nil, fmt.Errorf("read the invocation: %v", err)
	}
	if len(raw) > limit {
		return nil, errors.New("request exceeds the payload plus envelope byte bound")
	}
	return raw, nil
}

// harnessRequest is one validated invocation document.
type harnessRequest struct {
	invocation Invocation
	payload    []byte
	decoded    map[string]any
	budget     time.Duration
}

var harnessInstant = regexp.MustCompile("^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}([.][0-9]{1,9})?(Z|[+-][0-9]{2}:[0-9]{2})$")

// harnessRequestFields is the closed set of keys an invocation may carry. A key
// outside it is a launcher writing a framing this harness does not implement,
// which is refused rather than ignored.
var harnessRequestFields = map[string]bool{
	"protocol": true, "runnable": true, "invocation_id": true, "intent_id": true,
	"effect_id": true, "issued_at": true, "deadline": true, "input": true,
}

func harnessParseRequest(raw []byte) (harnessRequest, error) {
	var empty harnessRequest
	value, err := harnessDecode(raw)
	if err != nil {
		return empty, fmt.Errorf("request is not UTF-8 JSON: %v", err)
	}
	document, ok := value.(map[string]any)
	if !ok {
		return empty, errors.New("request must be an object")
	}
	if document["protocol"] != harnessProtocol {
		return empty, fmt.Errorf("request protocol %v is not %q", document["protocol"], harnessProtocol)
	}
	for key := range document {
		if !harnessRequestFields[key] {
			return empty, fmt.Errorf("request carries the undeclared field %q", key)
		}
	}
	id, err := harnessIdentifier(document, "invocation_id", true)
	if err != nil {
		return empty, err
	}
	intent, err := harnessIdentifier(document, "intent_id", true)
	if err != nil {
		return empty, err
	}
	effect, err := harnessIdentifier(document, "effect_id", false)
	if err != nil {
		return empty, err
	}
	// An effect identity is what an uncertain outcome of an effectful
	// operation is resolved with, so a package declaring receipt recovery
	// cannot run an invocation that carries none.
	if harnessRecovery == "receipt" && effect == "" {
		return empty, errors.New("effect_id is required for receipt recovery")
	}
	release, err := harnessReleaseOf(document["runnable"])
	if err != nil {
		return empty, err
	}
	issued, err := harnessTimestamp(document, "issued_at")
	if err != nil {
		return empty, err
	}
	deadline, err := harnessTimestamp(document, "deadline")
	if err != nil {
		return empty, err
	}
	if !deadline.After(issued) {
		return empty, errors.New("request.deadline must be after issued_at")
	}
	payload, err := harnessPayload(document["input"])
	if err != nil {
		return empty, err
	}
	decoded, err := harnessDecode(payload)
	if err != nil {
		return empty, fmt.Errorf("request.input is not UTF-8 JSON: %v", err)
	}
	object, ok := decoded.(map[string]any)
	if !ok {
		return empty, errors.New("request.input must decode to one JSON object")
	}
	return harnessRequest{
		invocation: Invocation{ID: id, IntentID: intent, EffectID: effect, Release: release, Deadline: deadline},
		payload:    payload,
		decoded:    object,
		// The budget is the span the caller allowed, measured from the moment
		// this harness read the document rather than against the local clock.
		// An offset between the launcher's clock and this one then neither
		// shortens nor extends the work the caller asked for.
		budget: deadline.Sub(issued),
	}, nil
}

func harnessIdentifier(document map[string]any, key string, required bool) (string, error) {
	raw, carried := document[key]
	if !carried {
		if required {
			return "", fmt.Errorf("request.%s is required", key)
		}
		return "", nil
	}
	value, ok := raw.(string)
	if !ok || len(value) > 128 || (required && value == "") {
		bound := "0"
		if required {
			bound = "1"
		}
		return "", fmt.Errorf("request.%s must contain %s to 128 characters", key, bound)
	}
	return value, nil
}

func harnessReleaseOf(raw any) (Release, error) {
	var empty Release
	document, ok := raw.(map[string]any)
	if !ok {
		return empty, errors.New("request.runnable requires name, module, workspace and version")
	}
	fields := map[string]string{}
	for _, key := range []string{"name", "module", "workspace", "version"} {
		value, carried := document[key].(string)
		if !carried || value == "" {
			return empty, errors.New("request.runnable identity fields must be nonempty strings")
		}
		fields[key] = value
	}
	if len(document) != len(fields) {
		return empty, errors.New("request.runnable requires name, module, workspace and version")
	}
	release := Release{Name: fields["name"], Module: fields["module"], Workspace: fields["workspace"], Version: fields["version"]}
	expected := harnessRelease
	// Standalone generation has no resolved workspace to compare against.
	if expected.Workspace == "" {
		expected.Workspace = release.Workspace
	}
	if release != expected {
		return empty, errors.New("request names another Runnable release")
	}
	return release, nil
}

func harnessTimestamp(document map[string]any, key string) (time.Time, error) {
	raw, ok := document[key].(string)
	if !ok || raw == "" {
		return time.Time{}, fmt.Errorf("request.%s is required", key)
	}
	if !harnessInstant.MatchString(raw) {
		return time.Time{}, fmt.Errorf("request.%s is not an RFC 3339 instant", key)
	}
	value, err := time.Parse(time.RFC3339Nano, raw)
	if err != nil {
		return time.Time{}, fmt.Errorf("request.%s is not an RFC 3339 instant", key)
	}
	return value.UTC(), nil
}

func harnessPayload(raw any) ([]byte, error) {
	encoded, ok := raw.(string)
	if !ok {
		return nil, errors.New("request.input must be base64 text")
	}
	payload, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("request.input is not base64: %v", err)
	}
	if len(payload) > harnessMaxInputBytes {
		return nil, fmt.Errorf("input is %d bytes, over the declared %d byte bound", len(payload), harnessMaxInputBytes)
	}
	return payload, nil
}

// harnessInvoke validates the payload, runs the handler under the caller's
// budget and validates what it returned.
func harnessInvoke(request harnessRequest, interrupted chan os.Signal) harnessOutcome {
	if err := harnessValidate(harnessInputSchema, request.decoded, "input"); err != nil {
		return harnessOutcome{code: harnessExitInvalidInput, diagnostic: "invalid_input: " + err.Error()}
	}
	var in Input
	// The schema admitted the payload, so a binding refusing it is a state the
	// contract forbids that the schema alone does not describe.
	if err := json.Unmarshal(request.payload, &in); err != nil {
		return harnessOutcome{code: harnessExitInvalidInput, diagnostic: "invalid_input: " + err.Error()}
	}

	result, out := harnessRun(request, in, interrupted)
	if result.code != harnessExitCompleted {
		return result
	}
	encoded, err := json.Marshal(out)
	if err != nil {
		return harnessOutcome{code: harnessExitInvalidOutput, diagnostic: "invalid_output: " + err.Error()}
	}
	if len(encoded) > harnessMaxOutputBytes {
		return harnessOutcome{code: harnessExitInvalidOutput,
			diagnostic: fmt.Sprintf("invalid_output: output is %d bytes, over the declared %d byte bound", len(encoded), harnessMaxOutputBytes)}
	}
	decoded, err := harnessDecode(encoded)
	if err != nil {
		return harnessOutcome{code: harnessExitInvalidOutput, diagnostic: "invalid_output: " + err.Error()}
	}
	object, ok := decoded.(map[string]any)
	if !ok {
		return harnessOutcome{code: harnessExitInvalidOutput, diagnostic: "invalid_output: output must be one JSON object"}
	}
	if err := harnessValidate(harnessOutputSchema, object, "output"); err != nil {
		return harnessOutcome{code: harnessExitInvalidOutput, diagnostic: "invalid_output: " + err.Error()}
	}
	result.encoded = encoded
	return result
}

// harnessRun calls the handler under the caller's budget, and under the
// interruption the declaration says this operation can take.
//
// The handler runs on its own goroutine because Go cannot raise into one: when
// the budget passes or a signal arrives, the process reports that and exits
// while the handler is still running. What it would have returned is no longer
// this invocation's outcome, which is why the reason that ended the wait wins
// over anything the handler produces afterwards.
func harnessRun(request harnessRequest, in Input, interrupted chan os.Signal) (harnessOutcome, Output) {
	ctx, cancel := context.WithTimeout(context.Background(), request.budget)
	defer cancel()
	ctx = context.WithValue(ctx, harnessInvocationKey{}, request.invocation)

	type handled struct {
		outcome harnessOutcome
		output  Output
	}
	completed := make(chan handled, 1)
	go func() {
		defer func() {
			// A panic leaves the effect unproven, not failed, so it writes no
			// result.
			if recovered := recover(); recovered != nil {
				completed <- handled{outcome: harnessOutcome{code: harnessExitFailed,
					diagnostic: fmt.Sprintf("failed: the handler panicked: %v", recovered)}}
			}
		}()
		out, err := Handle(ctx, in)
		var failure *Failure
		switch {
		case err == nil:
			completed <- handled{outcome: harnessOutcome{code: harnessExitCompleted}, output: out}
		case errors.As(err, &failure):
			completed <- handled{outcome: harnessOutcome{code: harnessExitFailed, failure: failure,
				diagnostic: "failed: " + failure.Error()}}
		default:
			completed <- handled{outcome: harnessOutcome{code: harnessExitFailed, diagnostic: "failed: " + err.Error()}}
		}
	}()

	var zero Output
	timedOut := harnessOutcome{code: harnessExitTimeout, diagnostic: "timeout: the deadline passed"}
	stopped := harnessOutcome{code: harnessExitInterrupted, diagnostic: "interrupted: the invocation was interrupted"}
	select {
	case result := <-completed:
		// A handler that swallowed the signal and returned anyway does not
		// turn an interruption into a completion. The deadline needs no such
		// check: once the budget passes this select has already returned, so a
		// result arriving here is one the handler produced while it still had
		// the time. Re-reading the clock instead would discard a completion
		// that beat the deadline but reached this line after it.
		select {
		case <-interrupted:
			return stopped, zero
		default:
		}
		return result.outcome, result.output
	case <-interrupted:
		return stopped, zero
	case <-ctx.Done():
		return timedOut, zero
	}
}

// harnessResultDocument renders what the harness proved, and reports whether
// there is anything to write. Only a validated success, an explicit failure and
// a handled interruption are reported; every other outcome leaves the effect
// unproven and writes nothing.
func harnessResultDocument(request harnessRequest, result harnessOutcome) (map[string]any, bool) {
	document := map[string]any{"protocol": harnessProtocol, "invocation_id": request.invocation.ID}
	switch {
	case result.code == harnessExitCompleted:
		document["status"] = "SUCCEEDED"
		document["output"] = base64.StdEncoding.EncodeToString(result.encoded)
	case result.failure != nil:
		document["status"] = "FAILED"
		document["error"] = map[string]any{"code": result.failure.Code, "message": result.failure.Message}
	case result.code == harnessExitInterrupted:
		document["status"] = "INTERRUPTED"
	default:
		return nil, false
	}
	return document, true
}

// harnessWriteResult renames a complete document onto the result path, so a
// document that exists is never a partial one.
func harnessWriteResult(path string, document map[string]any) error {
	encoded, err := json.Marshal(document)
	if err != nil {
		return err
	}
	staging, err := os.CreateTemp(filepath.Dir(path), ".result-")
	if err != nil {
		return err
	}
	name := staging.Name()
	defer os.Remove(name)
	if _, err := staging.Write(encoded); err != nil {
		staging.Close()
		return err
	}
	if err := staging.Sync(); err != nil {
		staging.Close()
		return err
	}
	if err := staging.Close(); err != nil {
		return err
	}
	if err := os.Chmod(name, harnessResultMode); err != nil {
		return err
	}
	return os.Rename(name, path)
}

// harnessField is one field of the bounded profile.
type harnessField struct {
	name     string
	kind     string
	optional bool
	nullable bool
	fields   []harnessField
	items    *harnessField
}

// harnessValidate reports the first way a payload fails the schema, naming the
// path it failed at.
func harnessValidate(fields []harnessField, payload any, at string) error {
	object, ok := payload.(map[string]any)
	if !ok {
		return fmt.Errorf("%s must be an object, got %s", at, harnessKindOf(payload))
	}
	declared := make(map[string]bool, len(fields))
	for _, field := range fields {
		declared[field.name] = true
	}
	for key := range object {
		if !declared[key] {
			return fmt.Errorf("%s.%s is not declared by the contract", at, key)
		}
	}
	for _, field := range fields {
		value, carried := object[field.name]
		if !carried {
			if field.optional {
				continue
			}
			return fmt.Errorf("%s.%s is required", at, field.name)
		}
		if err := harnessValidateValue(field, value, at+"."+field.name); err != nil {
			return err
		}
	}
	return nil
}

func harnessValidateValue(field harnessField, value any, at string) error {
	if value == nil {
		if field.nullable {
			return nil
		}
		return fmt.Errorf("%s is null but the contract does not declare it nullable", at)
	}
	switch field.kind {
	case "object":
		return harnessValidate(field.fields, value, at)
	case "array":
		elements, ok := value.([]any)
		if !ok {
			return fmt.Errorf("%s must be an array, got %s", at, harnessKindOf(value))
		}
		for index, element := range elements {
			if err := harnessValidateValue(*field.items, element, fmt.Sprintf("%s[%d]", at, index)); err != nil {
				return err
			}
		}
		return nil
	case "boolean":
		if _, ok := value.(bool); !ok {
			return fmt.Errorf("%s must be a boolean, got %s", at, harnessKindOf(value))
		}
		return nil
	case "integer":
		number, ok := value.(json.Number)
		if !ok || !harnessIsInteger(number) {
			return fmt.Errorf("%s must be an integer, got %s", at, harnessKindOf(value))
		}
		if _, err := number.Int64(); err != nil {
			return fmt.Errorf("%s is outside the signed 64-bit integer range", at)
		}
		return nil
	default:
		if _, ok := value.(string); !ok {
			return fmt.Errorf("%s must be a string, got %s", at, harnessKindOf(value))
		}
		return nil
	}
}

// harnessIsInteger reports whether a JSON number was written as one. The
// bounded profile has no number type, so 3.0 is not an integer spelled another
// way: it is a value the contract does not have.
func harnessIsInteger(number json.Number) bool {
	return !strings.ContainsAny(number.String(), ".eE")
}

func harnessKindOf(value any) string {
	switch typed := value.(type) {
	case nil:
		return "null"
	case bool:
		return "boolean"
	case json.Number:
		if harnessIsInteger(typed) {
			return "integer"
		}
		return "number"
	case string:
		return "string"
	case []any:
		return "array"
	case map[string]any:
		return "object"
	}
	return fmt.Sprintf("%T", value)
}

// harnessDecode decodes one JSON document, refusing a duplicate key and
// trailing content. encoding/json keeps the last of a repeated key, which would
// let one document mean two things to two readers; numbers are kept as written,
// so the profile's integer stays distinct from a number carrying a fraction.
func harnessDecode(raw []byte) (any, error) {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()
	value, err := harnessDecodeValue(decoder)
	if err != nil {
		return nil, err
	}
	if _, err := decoder.Token(); !errors.Is(err, io.EOF) {
		return nil, errors.New("document carries trailing content")
	}
	return value, nil
}

func harnessDecodeValue(decoder *json.Decoder) (any, error) {
	token, err := decoder.Token()
	if err != nil {
		return nil, err
	}
	delimiter, isDelimiter := token.(json.Delim)
	if !isDelimiter {
		return token, nil
	}
	if delimiter == '{' {
		object := map[string]any{}
		for decoder.More() {
			key, err := decoder.Token()
			if err != nil {
				return nil, err
			}
			name, ok := key.(string)
			if !ok {
				return nil, errors.New("object key is not a string")
			}
			if _, repeated := object[name]; repeated {
				return nil, fmt.Errorf("duplicate JSON key %q", name)
			}
			value, err := harnessDecodeValue(decoder)
			if err != nil {
				return nil, err
			}
			object[name] = value
		}
		if _, err := decoder.Token(); err != nil {
			return nil, err
		}
		return object, nil
	}
	array := []any{}
	for decoder.More() {
		value, err := harnessDecodeValue(decoder)
		if err != nil {
			return nil, err
		}
		array = append(array, value)
	}
	if _, err := decoder.Token(); err != nil {
		return nil, err
	}
	return array, nil
}
`
