package generate

import (
	"fmt"
	"go/format"
	"strings"

	basev0 "github.com/codefly-dev/core/generated/go/codefly/base/v0"
	"github.com/codefly-dev/core/resources"
	corerunnable "github.com/codefly-dev/core/runnable"
)

// Files of the generated invocation harness.
const (
	// HarnessFile carries the harness, beside the bindings and the handler it
	// runs. It is in the author's own package rather than a subpackage so the
	// invocation identity can reach the handler through its context without an
	// exported setter the author could call by mistake.
	HarnessFile = "harness.go"
	// CommandDirectory holds the executable that serves the runnable. The Go tool
	// ignores a directory whose name begins with a dot or an underscore, so
	// this one cannot be spelled the way the Python agent spells its generated
	// directory.
	CommandDirectory = "codefly"
	// CommandFile is that executable's main package.
	CommandFile = "main.go"
)

// Harness renders the invocation harness of a runnable: the served routes, the
// payload validation the bindings do not do, and the call lifecycle a caller
// observes.
//
// Every fact the harness enforces is rendered into it rather than read at
// runtime from a document beside it. A Go runnable is compiled, so a contract
// carried in a file could be edited after the build that measured it while the
// binary went on honoring the edit; compiled in, the bounds and the release
// identity are covered by the digest of the artifact that carries them.
//
// identity is the release the workspace resolved. Standalone generation has no
// owning workspace and passes nil, which leaves the workspace unchecked at
// invocation time — the same allowance the Python agent makes, because there is
// no resolved workspace to check against.
func Harness(pkg string, runnable *resources.Runnable, identity *basev0.RunnableIdentity) ([]byte, error) {
	if err := validatePackageName(pkg); err != nil {
		return nil, err
	}
	if err := runnable.Contract.Validate(); err != nil {
		return nil, err
	}
	if err := runnable.Execution.Validate(); err != nil {
		return nil, err
	}
	release := runnable.Identity()
	name, module, workspace, version := release.Name, release.Module, "", runnable.Version
	if identity != nil {
		name, module, workspace, version = identity.GetName(), identity.GetModule(), identity.GetWorkspace(), identity.GetVersion()
	}

	var b strings.Builder
	fmt.Fprintf(&b, "//go:build %s\n\n", GoRequirement)
	b.WriteString("// Code generated by runnable-go. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString(harnessImports)

	b.WriteString("\n// The framing this harness implements, and the bounds and policies its\n")
	b.WriteString("// declaration sets. They are constants so the binary cannot be pointed at a\n")
	b.WriteString("// contract other than the one the build measured.\nconst (\n")
	fmt.Fprintf(&b, "\tharnessProtocol = %q\n", resources.RunnableServedProtocolV1)
	fmt.Fprintf(&b, "\tharnessMaxInputBytes = %d\n", runnable.Execution.MaxInputBytes())
	fmt.Fprintf(&b, "\tharnessMaxOutputBytes = %d\n", runnable.Execution.MaxOutputBytes())
	fmt.Fprintf(&b, "\tharnessRecovery = %q\n", string(runnable.Execution.Recovery))
	fmt.Fprintf(&b, "\tharnessCancellation = %q\n", string(runnable.Execution.Cancellation))
	// The declared timeout bounds one call. It is compiled in for the same
	// reason the bounds are: a caller may shorten it with a deadline header and
	// may never overrule the author with a longer one.
	fmt.Fprintf(&b, "\tharnessDeclaredTimeout = %d * time.Nanosecond\n", runnable.Execution.GetTimeout())
	b.WriteString(")\n")

	b.WriteString("\n// harnessRelease is the release this package implements. An invocation\n")
	b.WriteString("// naming another release is refused rather than run against foreign input,\n")
	b.WriteString("// which is what keeps two installed versions of one runnable apart.\n")
	fmt.Fprintf(&b, "var harnessRelease = Release{Name: %q, Module: %q, Workspace: %q, Version: %q}\n",
		name, module, workspace, version)

	b.WriteString("\n// The declared schemas, enforced against the raw payload before it is\n")
	b.WriteString("// decoded: the bindings carry value types and null states, not required\n")
	b.WriteString("// keys, undeclared keys or the signed 64-bit integer range.\n")
	b.WriteString("var harnessInputSchema = ")
	b.WriteString(renderFields(runnable.Contract.Input.Fields, 0))
	b.WriteString("\n\nvar harnessOutputSchema = ")
	b.WriteString(renderFields(runnable.Contract.Output.Fields, 0))
	b.WriteString("\n")
	b.WriteString(harnessBody)
	// The receipt route is the one place the two shapes of the harness differ.
	// A package whose uncertain outcome is resolved by recomputing has no
	// receipt to serve and no ReceiptOf for the route to call, so rendering it
	// anyway would not compile.
	if runnable.Execution.Recovery == resources.RunnableRecoveryReceipt {
		b.WriteString(harnessReceiptBody)
	} else {
		b.WriteString(harnessNoReceiptBody)
	}
	return format.Source([]byte(b.String()))
}

// Command renders the executable that serves this runnable. It is a separate
// main package because the harness shares the author's package, and a package
// that is imported cannot also be a main.
func Command(pkg string) ([]byte, error) {
	if err := validatePackageName(pkg); err != nil {
		return nil, err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "//go:build %s\n\n", GoRequirement)
	b.WriteString("// Code generated by runnable-go. DO NOT EDIT.\n\n")
	b.WriteString("// Command codefly serves the runnable's operation.\npackage main\n\n")
	fmt.Fprintf(&b, "import (\n\t\"os\"\n\n\t%q\n)\n\n", pkg)
	fmt.Fprintf(&b, "func main() {\n\tos.Exit(%s.Main())\n}\n", pkg)
	return format.Source([]byte(b.String()))
}

// renderFields renders one schema as a Go literal.
func renderFields(fields []*resources.RunnableField, depth int) string {
	if len(fields) == 0 {
		return "[]harnessField{}"
	}
	pad := strings.Repeat("\t", depth+1)
	var b strings.Builder
	b.WriteString("[]harnessField{\n")
	for _, field := range fields {
		b.WriteString(pad)
		b.WriteString(renderField(field, depth+1))
		b.WriteString(",\n")
	}
	b.WriteString(strings.Repeat("\t", depth))
	b.WriteString("}")
	return b.String()
}

func renderField(field *resources.RunnableField, depth int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "{name: %q, kind: %q", field.Name, string(field.Type))
	if field.Optional {
		b.WriteString(", optional: true")
	}
	if field.Nullable {
		b.WriteString(", nullable: true")
	}
	switch field.Type {
	case resources.RunnableFieldObject:
		b.WriteString(", fields: ")
		b.WriteString(renderFields(field.Fields, depth))
	case resources.RunnableFieldArray:
		b.WriteString(", items: &harnessField")
		b.WriteString(renderField(field.Items, depth))
	}
	b.WriteString("}")
	return b.String()
}

const harnessImports = `import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"sync"
	"syscall"
	"time"
)
`

// harnessBody is the part of the harness that does not vary with the contract.
//
// Every declaration it makes beyond the handler's own surface is prefixed,
// because the harness shares the author's package: an unprefixed helper named
// request or validate would collide with whatever the author wrote beside it.
//
// It carries no backquote, being itself a Go raw string literal.
const harnessBody = `
// The address this harness listens on. It is the one fact it cannot derive:
// the port is allocated by whatever placed it, and a harness choosing its own
// would be a port that is right on one machine for ten minutes.
const harnessEnvAddress = "` + corerunnable.ListenAddressEnv + `"

// The routes it serves, and the headers one call's per-call facts travel under.
// All six are core's constants (codefly-dev/core runnable/served.go), restated
// here because a generated harness carries no import of core: the binding that
// dials this harness names the same strings, and a harness serving one spelling
// while its binding names another is an unreachable owner rather than a visible
// mistake.
const (
	harnessInvokeProcedure = "` + corerunnable.ServedInvokeProcedure + `"
	harnessLookupProcedure = "` + corerunnable.ServedLookupProcedure + `"

	harnessWorkContextHeader = "` + corerunnable.WorkContextHeader + `"
	harnessEffectHeader      = "` + corerunnable.EffectHeader + `"
	harnessDeadlineHeader    = "` + corerunnable.DeadlineHeader + `"
	harnessFailureCodeHeader = "` + corerunnable.FailureCodeHeader + `"
)

// harnessEnvelopeBytes is how much framing is read around the payload bound, so
// an oversized request is refused without being read whole.
const harnessEnvelopeBytes = 64 * 1024

// harnessShutdownGrace is how long a call in flight has to finish after a
// signal. A handler interrupted mid-effect leaves it unproven, so the process
// waits rather than making every call in flight unproven at once.
const harnessShutdownGrace = 30 * time.Second

// Release identifies a runnable release.
type Release struct {
	Name      string
	Module    string
	Workspace string
	Version   string
}

// Invocation is what the caller said about this call. The identity is the
// caller's: an effect recorded under EffectID is the one the caller looks up
// when an outcome is uncertain.
//
// WorkContext is the caller's minted capability, carried verbatim. It is never
// parsed or reconstructed here — a handler forwards it to whatever it calls in
// turn, and that is the whole of what this harness does with it.
type Invocation struct {
	ID          string
	IntentID    string
	EffectID    string
	Release     Release
	Deadline    time.Time
	WorkContext string
}

type harnessInvocationKey struct{}

// InvocationFrom returns the invocation the handler is running under.
func InvocationFrom(ctx context.Context) (Invocation, bool) {
	invocation, ok := ctx.Value(harnessInvocationKey{}).(Invocation)
	return invocation, ok
}

// Failure is an operation's explicit, certain failure: the handler knows what
// became of the effect. It is the ONLY thing that sets the failure-code header,
// and that header is the only thing that proves to a caller that nothing
// committed. Every other error — a panic, a deadline, an output that does not
// validate — leaves the effect unproven, because the harness cannot know which
// side of its effect the handler stopped on.
type Failure struct {
	Code    string
	Message string
}

func (f *Failure) Error() string {
	return f.Code + ": " + f.Message
}

// Fail returns the error a handler returns to report a certain failure.
func Fail(code string, message string) error {
	return &Failure{Code: code, Message: message}
}

// Main serves this runnable until it is signalled, and returns the process exit
// code. One call carries one invocation; nothing here is per-process state, so
// concurrent calls are independent.
func Main() int {
	address := os.Getenv(harnessEnvAddress)
	if address == "" {
		fmt.Fprintf(os.Stderr, "[codefly] %s is required: the port is allocated by whatever placed this runnable\n", harnessEnvAddress)
		return 1
	}

	mux := http.NewServeMux()
	mux.HandleFunc(harnessInvokeProcedure, harnessServeInvoke)
	harnessServeReceipts(mux)
	server := &http.Server{Addr: address, Handler: mux, ReadHeaderTimeout: 10 * time.Second}

	signalled := make(chan os.Signal, 1)
	signal.Notify(signalled, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(signalled)

	var once sync.Once
	failed := make(chan error, 1)
	go func() {
		if err := server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			failed <- err
		}
	}()

	code := 0
	select {
	case err := <-failed:
		fmt.Fprintf(os.Stderr, "[codefly] serve: %v\n", err)
		code = 1
	case <-signalled:
		// Calls already in flight are given their grace: cutting them off would
		// turn every one of them into an unproven effect at once, which is the
		// outcome this harness spends the rest of its code avoiding.
		ctx, cancel := context.WithTimeout(context.Background(), harnessShutdownGrace)
		defer cancel()
		once.Do(func() {
			if err := server.Shutdown(ctx); err != nil {
				fmt.Fprintf(os.Stderr, "[codefly] shutdown: %v\n", err)
				code = 1
			}
		})
	}
	return code
}

// harnessServeInvoke answers one call. The body is the bounded input document
// itself, with no envelope around it, and a success answers with the bounded
// output document the same way.
func harnessServeInvoke(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		harnessUnproven(w, http.StatusMethodNotAllowed, "unimplemented", "the operation is called with POST")
		return
	}
	request, err := harnessReadCall(r)
	if err != nil {
		// Nothing reached the handler, so nothing committed — but "proven not
		// committed" is the owner asserting it in the operation's own
		// vocabulary, and a refused request is not the operation speaking. A
		// caller reads this as unproven and retries under its budget, which is
		// harmless for a request that never ran.
		harnessUnproven(w, http.StatusBadRequest, "invalid_argument", err.Error())
		return
	}

	result := harnessRun(r.Context(), request)
	switch {
	case result.failure != nil:
		harnessProvenFailure(w, result.failure)
	case result.code == harnessExitCompleted:
		harnessAnswer(w, result.encoded)
	case result.code == harnessExitTimeout:
		harnessUnproven(w, http.StatusGatewayTimeout, "deadline_exceeded", result.diagnostic)
	case result.code == harnessExitInvalidInput:
		harnessUnproven(w, http.StatusBadRequest, "invalid_argument", result.diagnostic)
	default:
		harnessUnproven(w, http.StatusInternalServerError, "internal", result.diagnostic)
	}
	if result.diagnostic != "" {
		fmt.Fprintf(os.Stderr, "[codefly] %s\n", result.diagnostic)
	}
}

// harnessCall is one validated call.
type harnessCall struct {
	invocation Invocation
	input      Input
	decoded    map[string]any
	budget     time.Duration
}

// harnessReadCall reads and validates the per-call facts and the bounded body.
func harnessReadCall(r *http.Request) (harnessCall, error) {
	var empty harnessCall
	limit := harnessMaxInputBytes + harnessEnvelopeBytes
	raw, err := io.ReadAll(io.LimitReader(r.Body, int64(limit)+1))
	if err != nil {
		return empty, fmt.Errorf("read the request: %v", err)
	}
	if len(raw) > harnessMaxInputBytes {
		return empty, fmt.Errorf("input is %d bytes, over the declared %d byte bound", len(raw), harnessMaxInputBytes)
	}

	workContext := r.Header.Get(harnessWorkContextHeader)
	if workContext == "" {
		// A call with no identity is the one thing the contract exists to
		// prevent, so it is refused rather than run under whatever identity
		// this process happens to have.
		return empty, errors.New("the call carries no Work Context")
	}
	effect := r.Header.Get(harnessEffectHeader)
	if harnessRecovery == "receipt" && effect == "" {
		return empty, errors.New("an effect identity is required for receipt recovery")
	}

	// The deadline bounds the work. It is optional on the wire because a caller
	// may not have one; absent, the declared timeout is the bound, which is the
	// author's own statement about how long this operation may run.
	budget := harnessDeclaredTimeout
	if raw := r.Header.Get(harnessDeadlineHeader); raw != "" {
		deadline, err := time.Parse(time.RFC3339Nano, raw)
		if err != nil {
			return empty, fmt.Errorf("%s is not an RFC 3339 instant", harnessDeadlineHeader)
		}
		// Measured from now rather than from an instant the caller stamped, so
		// an offset between the two clocks neither shortens nor extends the
		// work the caller asked for beyond what it actually still allows.
		if budget = time.Until(deadline); budget <= 0 {
			return empty, errors.New("the deadline had passed before the call was read")
		}
		if budget > harnessDeclaredTimeout {
			budget = harnessDeclaredTimeout
		}
	}

	decoded, err := harnessDecode(raw)
	if err != nil {
		return empty, fmt.Errorf("request body is not UTF-8 JSON: %v", err)
	}
	object, ok := decoded.(map[string]any)
	if !ok {
		return empty, errors.New("request body must be one JSON object")
	}
	if err := harnessValidate(harnessInputSchema, object, "input"); err != nil {
		return empty, err
	}
	var in Input
	// The schema admitted the payload, so a binding refusing it is a state the
	// contract forbids that the schema alone does not describe.
	if err := json.Unmarshal(raw, &in); err != nil {
		return empty, fmt.Errorf("input: %v", err)
	}
	return harnessCall{
		invocation: Invocation{
			EffectID:    effect,
			Release:     harnessRelease,
			Deadline:    time.Now().Add(budget),
			WorkContext: workContext,
		},
		input:   in,
		decoded: object,
		budget:  budget,
	}, nil
}

// harnessOutcome is what one call produced, before it becomes a response.
type harnessOutcome struct {
	code       int
	encoded    []byte
	failure    *Failure
	diagnostic string
}

// Outcomes a call can have. They are no longer process exit codes — nothing
// exits per call — but the distinctions are the ones a caller acts on, so they
// are kept rather than collapsed into an error string.
const (
	harnessExitCompleted     = 0
	harnessExitInvalidInput  = 64
	harnessExitInvalidOutput = 65
	harnessExitFailed        = 66
	harnessExitTimeout       = 67
)

// harnessRun calls the handler under the caller's budget and validates what it
// returned.
//
// The handler runs on its own goroutine because Go cannot raise into one: when
// the budget passes, this answers and the handler is still running. What it
// would have returned is no longer this call's outcome, which is why the
// deadline wins over anything the handler produces afterwards.
func harnessRun(parent context.Context, call harnessCall) harnessOutcome {
	ctx, cancel := context.WithTimeout(parent, call.budget)
	defer cancel()
	ctx = context.WithValue(ctx, harnessInvocationKey{}, call.invocation)

	type handled struct {
		outcome harnessOutcome
		output  Output
	}
	completed := make(chan handled, 1)
	go func() {
		defer func() {
			// A panic leaves the effect unproven, not failed: the handler never
			// said which side of its effect it stopped on.
			if recovered := recover(); recovered != nil {
				completed <- handled{outcome: harnessOutcome{code: harnessExitInvalidOutput,
					diagnostic: fmt.Sprintf("the handler panicked: %v", recovered)}}
			}
		}()
		out, err := Handle(ctx, call.input)
		var failure *Failure
		switch {
		case err == nil:
			completed <- handled{outcome: harnessOutcome{code: harnessExitCompleted}, output: out}
		case errors.As(err, &failure):
			completed <- handled{outcome: harnessOutcome{code: harnessExitFailed, failure: failure,
				diagnostic: "failed: " + failure.Error()}}
		default:
			// An untyped error is not the operation asserting anything, so it
			// stays unproven rather than being reported as a failure a caller
			// would read as proof no effect committed.
			completed <- handled{outcome: harnessOutcome{code: harnessExitInvalidOutput,
				diagnostic: "the handler returned an untyped error: " + err.Error()}}
		}
	}()

	select {
	case result := <-completed:
		if result.outcome.code != harnessExitCompleted {
			return result.outcome
		}
		encoded, err := harnessEncodeOutput(result.output)
		if err != nil {
			return harnessOutcome{code: harnessExitInvalidOutput, diagnostic: err.Error()}
		}
		result.outcome.encoded = encoded
		return result.outcome
	case <-ctx.Done():
		return harnessOutcome{code: harnessExitTimeout, diagnostic: "the deadline passed"}
	}
}

// harnessEncodeOutput renders and validates what the handler returned, so an
// answer a caller accepts is one that matches the installed contract.
func harnessEncodeOutput(out Output) ([]byte, error) {
	encoded, err := json.Marshal(out)
	if err != nil {
		return nil, fmt.Errorf("output: %v", err)
	}
	if len(encoded) > harnessMaxOutputBytes {
		return nil, fmt.Errorf("output is %d bytes, over the declared %d byte bound", len(encoded), harnessMaxOutputBytes)
	}
	decoded, err := harnessDecode(encoded)
	if err != nil {
		return nil, fmt.Errorf("output: %v", err)
	}
	object, ok := decoded.(map[string]any)
	if !ok {
		return nil, errors.New("output must be one JSON object")
	}
	if err := harnessValidate(harnessOutputSchema, object, "output"); err != nil {
		return nil, err
	}
	return encoded, nil
}

// harnessAnswer writes a success: the bounded output document itself, with no
// envelope around it.
func harnessAnswer(w http.ResponseWriter, encoded []byte) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(encoded)
}

// harnessProvenFailure writes the operation's own typed failure. The header is
// what makes it PROVEN that nothing committed — a caller reads it before the
// status, and without it no status proves anything — so it is set here and
// nowhere else in this harness.
func harnessProvenFailure(w http.ResponseWriter, failure *Failure) {
	w.Header().Set(harnessFailureCodeHeader, failure.Code)
	harnessUnproven(w, http.StatusUnprocessableEntity, "failed_precondition", failure.Message)
}

// harnessUnproven writes an error answer in the Connect JSON shape. On its own
// it proves nothing about the effect, which is the point: a caller that cannot
// see the operation's own assertion must treat the attempt as unresolved.
func harnessUnproven(w http.ResponseWriter, status int, code string, message string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	encoded, err := json.Marshal(map[string]any{"code": code, "message": message})
	if err != nil {
		return
	}
	w.Write(encoded)
}

// harnessField is one field of the bounded profile.
type harnessField struct {
	name     string
	kind     string
	optional bool
	nullable bool
	fields   []harnessField
	items    *harnessField
}

// harnessValidate reports the first way a payload fails the schema, naming the
// path it failed at.
func harnessValidate(fields []harnessField, payload any, at string) error {
	object, ok := payload.(map[string]any)
	if !ok {
		return fmt.Errorf("%s must be an object, got %s", at, harnessKindOf(payload))
	}
	declared := make(map[string]bool, len(fields))
	for _, field := range fields {
		declared[field.name] = true
	}
	for key := range object {
		if !declared[key] {
			return fmt.Errorf("%s.%s is not declared by the contract", at, key)
		}
	}
	for _, field := range fields {
		value, carried := object[field.name]
		if !carried {
			if field.optional {
				continue
			}
			return fmt.Errorf("%s.%s is required", at, field.name)
		}
		if err := harnessValidateValue(field, value, at+"."+field.name); err != nil {
			return err
		}
	}
	return nil
}

func harnessValidateValue(field harnessField, value any, at string) error {
	if value == nil {
		if field.nullable {
			return nil
		}
		return fmt.Errorf("%s is null but the contract does not declare it nullable", at)
	}
	switch field.kind {
	case "object":
		return harnessValidate(field.fields, value, at)
	case "array":
		elements, ok := value.([]any)
		if !ok {
			return fmt.Errorf("%s must be an array, got %s", at, harnessKindOf(value))
		}
		for index, element := range elements {
			if err := harnessValidateValue(*field.items, element, fmt.Sprintf("%s[%d]", at, index)); err != nil {
				return err
			}
		}
		return nil
	case "boolean":
		if _, ok := value.(bool); !ok {
			return fmt.Errorf("%s must be a boolean, got %s", at, harnessKindOf(value))
		}
		return nil
	case "integer":
		number, ok := value.(json.Number)
		if !ok || !harnessIsInteger(number) {
			return fmt.Errorf("%s must be an integer, got %s", at, harnessKindOf(value))
		}
		if _, err := number.Int64(); err != nil {
			return fmt.Errorf("%s is outside the signed 64-bit integer range", at)
		}
		return nil
	default:
		if _, ok := value.(string); !ok {
			return fmt.Errorf("%s must be a string, got %s", at, harnessKindOf(value))
		}
		return nil
	}
}

// harnessIsInteger reports whether a JSON number was written as one. The
// bounded profile has no number type, so 3.0 is not an integer spelled another
// way: it is a value the contract does not have.
func harnessIsInteger(number json.Number) bool {
	return !strings.ContainsAny(number.String(), ".eE")
}

func harnessKindOf(value any) string {
	switch typed := value.(type) {
	case nil:
		return "null"
	case bool:
		return "boolean"
	case json.Number:
		if harnessIsInteger(typed) {
			return "integer"
		}
		return "number"
	case string:
		return "string"
	case []any:
		return "array"
	case map[string]any:
		return "object"
	}
	return fmt.Sprintf("%T", value)
}

// harnessDecode decodes one JSON document, refusing a duplicate key and
// trailing content. encoding/json keeps the last of a repeated key, which would
// let one document mean two things to two readers; numbers are kept as written,
// so the profile's integer stays distinct from a number carrying a fraction.
func harnessDecode(raw []byte) (any, error) {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()
	value, err := harnessDecodeValue(decoder)
	if err != nil {
		return nil, err
	}
	if _, err := decoder.Token(); !errors.Is(err, io.EOF) {
		return nil, errors.New("document carries trailing content")
	}
	return value, nil
}

func harnessDecodeValue(decoder *json.Decoder) (any, error) {
	token, err := decoder.Token()
	if err != nil {
		return nil, err
	}
	delimiter, isDelimiter := token.(json.Delim)
	if !isDelimiter {
		return token, nil
	}
	if delimiter == '{' {
		object := map[string]any{}
		for decoder.More() {
			key, err := decoder.Token()
			if err != nil {
				return nil, err
			}
			name, ok := key.(string)
			if !ok {
				return nil, errors.New("object key is not a string")
			}
			if _, repeated := object[name]; repeated {
				return nil, fmt.Errorf("duplicate JSON key %q", name)
			}
			value, err := harnessDecodeValue(decoder)
			if err != nil {
				return nil, err
			}
			object[name] = value
		}
		if _, err := decoder.Token(); err != nil {
			return nil, err
		}
		return object, nil
	}
	array := []any{}
	for decoder.More() {
		value, err := harnessDecodeValue(decoder)
		if err != nil {
			return nil, err
		}
		array = append(array, value)
	}
	if _, err := decoder.Token(); err != nil {
		return nil, err
	}
	return array, nil
}
`

// harnessReceiptBody is rendered only for a package declaring receipt recovery:
// it is the receipt route and the Receipt type the author implements ReceiptOf
// against. A recompute package has no receipt to serve, and rendering a route
// that called a ReceiptOf the author never wrote would not compile.
const harnessReceiptBody = `
// Receipt is what an operation committed under one effect identity. A handler
// of a receipt-recovery operation implements ReceiptOf to answer a recovery:
// found reports the committed output, and absent is not an error — it is the
// answer the recovery exists to get, and it never means the effect did not
// happen.
type Receipt struct {
	Output Output
	Found  bool
}
// harnessServeLookup answers a recovery: what did this effect commit? Absent is
// answered with 404 and is never an error, because a caller reads an absent
// receipt as inconclusive rather than as permission to invoke again.
func harnessServeLookup(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		harnessUnproven(w, http.StatusMethodNotAllowed, "unimplemented", "the receipt route is called with POST")
		return
	}
	request, err := harnessReadCall(r)
	if err != nil {
		harnessUnproven(w, http.StatusBadRequest, "invalid_argument", err.Error())
		return
	}
	ctx := context.WithValue(r.Context(), harnessInvocationKey{}, request.invocation)
	receipt, err := ReceiptOf(ctx, request.input)
	if err != nil {
		harnessUnproven(w, http.StatusInternalServerError, "internal", "receipt: "+err.Error())
		return
	}
	if !receipt.Found {
		harnessUnproven(w, http.StatusNotFound, "not_found", "no receipt for this effect")
		return
	}
	encoded, err := harnessEncodeOutput(receipt.Output)
	if err != nil {
		harnessUnproven(w, http.StatusInternalServerError, "internal", "receipt: "+err.Error())
		return
	}
	harnessAnswer(w, encoded)
}
func harnessServeReceipts(mux *http.ServeMux) {
	mux.HandleFunc(harnessLookupProcedure, harnessServeLookup)
}
`

// harnessNoReceiptBody is its counterpart: a package whose uncertain outcome is
// resolved by recomputing has nothing to look up, so the route is absent rather
// than present and answering "never".
const harnessNoReceiptBody = `
func harnessServeReceipts(mux *http.ServeMux) {}
`
